import importlib.util
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = ROOT / "scripts" / "publish_client_code_ota_to_server.py"


def _load_publish_module():
    spec = importlib.util.spec_from_file_location("publish_client_code_ota_to_server", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def test_manifest_paths_only_include_files_present_in_ota(tmp_path):
    module = _load_publish_module()
    zip_path = tmp_path / "client-ota.zip"
    omitted_paths = {
        "nodejs/node_modules/@tencent-weixin/openclaw-weixin",
        "backend/douyin_origin/douyin_protocol/node_modules",
    }
    expected_paths = [
        path
        for path in module.DEFAULT_CLIENT_CODE_OTA_PATHS
        if path != "CLIENT_CODE_VERSION.json" and path not in omitted_paths
    ]

    with zipfile.ZipFile(zip_path, "w") as archive:
        for path in expected_paths:
            if "." in Path(path).name:
                archive.writestr(path, "test")
            else:
                archive.writestr(f"{path}/placeholder.txt", "test")
        archive.writestr("CLIENT_CODE_VERSION.json", "{}")

    paths = module.manifest_paths_for_zip(zip_path)

    assert ".env" not in paths
    assert "必火智能AI.exe" not in paths
    for path in omitted_paths:
        assert path not in paths
    with zipfile.ZipFile(zip_path) as archive:
        names = {name.rstrip("/") for name in archive.namelist()}
    for path in paths:
        normalized = path.replace("\\", "/").rstrip("/")
        assert normalized in names or any(name.startswith(normalized + "/") for name in names)


def test_plain_source_ota_is_rejected(tmp_path):
    module = _load_publish_module()
    zip_path = tmp_path / "plain.zip"
    with zipfile.ZipFile(zip_path, "w") as archive:
        archive.writestr("backend/app.py", "VALUE = 1\n")

    assert module.is_encrypted_ota_zip(zip_path) is False


def test_encrypted_loader_ota_is_accepted(tmp_path):
    module = _load_publish_module()
    zip_path = tmp_path / "encrypted.zip"
    with zipfile.ZipFile(zip_path, "w") as archive:
        archive.writestr(
            "backend/app.py",
            "# Auto-generated by scripts/pack_client_code_ota.py --encrypted.\n",
        )
        archive.writestr("backend/app.pyc", b"compiled")

    assert module.is_encrypted_ota_zip(zip_path) is True


def test_website_ota_manifest_keeps_static_paths_granular(tmp_path):
    module = _load_publish_module()
    zip_path = tmp_path / "website.zip"
    with zipfile.ZipFile(zip_path, "w") as archive:
        archive.writestr("backend/app.pyc", b"compiled")
        archive.writestr("static/js/app.js", "code")
        archive.writestr("static/css/common.css", "code")
        archive.writestr("static/index.html", "code")
        archive.writestr("static/client_version.json", "{}")
        archive.writestr("CLIENT_CODE_VERSION.json", "{}")

    paths = module.manifest_paths_for_zip(zip_path)

    assert "static" not in paths
    assert paths == [
        "backend",
        "static/css",
        "static/js",
        "static/index.html",
        "static/client_version.json",
        "CLIENT_CODE_VERSION.json",
    ]


def test_oem_switcher_website_ota_uses_exact_desktop_paths(tmp_path):
    module = _load_publish_module()
    zip_path = tmp_path / "oem-switcher.zip"
    with zipfile.ZipFile(zip_path, "w") as archive:
        archive.writestr("backend/app.py", "# Auto-generated by scripts/pack_client_code_ota.py --encrypted.\n")
        archive.writestr("backend/app.pyc", b"compiled")
        for path in module.OEM_SWITCHER_OTA_PATHS:
            archive.writestr(path, b"compiled" if path.endswith(".pyc") else "# Auto-generated by scripts/pack_client_code_ota.py --encrypted.\n")
        archive.writestr("CLIENT_CODE_VERSION.json", "{}")

    paths = module.manifest_paths_for_zip(zip_path)

    assert "desktop" not in paths
    assert module.OEM_SWITCHER_OTA_PATHS.issubset(paths)
