(function () {
  'use strict';
  var state={rows:[],open:false,seenActive:{},polling:false};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function auth(){var token='';try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i)||'';if(k.indexOf('lobster_h5_token')===0){token=localStorage.getItem(k)||'';break;}}}catch(_){}return token?{Authorization:'Bearer '+token}:{};}
  function active(row){return ['pending','processing','running','claimed','queued'].indexOf(String(row.status||'').toLowerCase())>=0;}
  function title(row){return row.title||row.task_title||row.name||'正在执行的任务';}
  function message(row){var p=row.progress||row.result_payload||{};return row.message||row.status_text||p.message||p.text||row.last_error||(active(row)?'正在处理，请保持设备在线':'任务已结束');}
  function percent(row){var p=row.progress||row.result_payload||{},total=Number(row.total||p.total||0),done=Number(row.processed||p.processed||p.current||0);return total>0?Math.max(3,Math.min(100,Math.round(done*100/total))):(active(row)?32:100);}
  function mount(){if(document.getElementById('lobsterTaskFab'))return;var root=document.createElement('div');root.innerHTML='<button id="lobsterTaskFab" class="lobster-task-fab" type="button" aria-label="任务中心" title="任务中心"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h14v14H5zM9 9h6v6H9z"></path></svg><i></i></button><section id="lobsterTaskPanel" class="lobster-task-panel" hidden><header class="lobster-task-head"><div><strong>任务中心</strong><span id="lobsterTaskHint">正在同步任务状态</span></div><button class="lobster-task-close" type="button" aria-label="关闭">×</button></header><div id="lobsterTaskList" class="lobster-task-list"></div></section>';document.body.appendChild(root);root.querySelector('#lobsterTaskFab').onclick=function(){state.open=!state.open;render();};root.querySelector('.lobster-task-close').onclick=function(){state.open=false;render();};root.querySelector('#lobsterTaskList').onclick=stop;}
  function render(){var panel=document.getElementById('lobsterTaskPanel'),fab=document.getElementById('lobsterTaskFab'),list=document.getElementById('lobsterTaskList'),hint=document.getElementById('lobsterTaskHint');if(!panel||!fab||!list)return;var running=state.rows.filter(active);fab.classList.toggle('is-active',!!running.length);panel.hidden=!state.open;hint.textContent=running.length?running.length+' 项任务正在执行':'当前没有执行中的任务';list.innerHTML=running.length?running.slice(0,5).map(function(row){var p=percent(row);return '<article class="lobster-task-card" style="--task-progress:'+p+'%"><div class="lobster-task-row"><div class="lobster-task-copy"><div class="lobster-task-title">'+esc(title(row))+'</div><div class="lobster-task-message">'+esc(message(row))+'</div><div class="lobster-task-meta">执行中 · '+p+'%</div></div>'+(row.id?'<button class="lobster-task-stop" data-run-id="'+esc(row.id)+'" type="button">停止</button>':'')+'</div><div class="lobster-task-track"><i></i></div></article>';}).join(''):'<div class="lobster-task-empty">当前没有执行中的任务</div>';}
  async function refresh(){if(state.polling)return;state.polling=true;try{var r=await fetch('/api/scheduled-tasks/runs?limit=20',{headers:auth()});if(!r.ok)throw new Error();var d=await r.json(),rows=Array.isArray(d.runs)?d.runs:[],running=rows.filter(active),fresh=running.some(function(row){return row.id&&!state.seenActive[row.id];});state.seenActive={};running.forEach(function(row){if(row.id)state.seenActive[row.id]=true;});state.rows=rows;if(fresh)state.open=true;render();}catch(_){}finally{state.polling=false;}}
  async function stop(evt){var btn=evt.target.closest('[data-run-id]');if(!btn)return;btn.disabled=true;btn.textContent='停止中';try{var r=await fetch('/api/scheduled-tasks/runs/'+encodeURIComponent(btn.dataset.runId),{method:'DELETE',headers:auth()});if(!r.ok)throw new Error();await refresh();}catch(_){btn.disabled=false;btn.textContent='停止失败';}}
  function start(){mount();refresh();setInterval(refresh,4000);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
